# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn build
  displayName: 'Build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build'
    Contents: '**'
    TargetFolder: '$(System.DefaultWorkingDirectory)/web'
  displayName: 'CopyFiles'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/web'
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/web_$(Build.BuildNumber)-master.zip'
    replaceExistingArchive: true
  displayName: 'ArchiveFiles'

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
  displayName: 'PublishBuildArtifacts'